#!/usr/bin/env python3
"""Generate English pages from Russian templates."""
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent

SUBJ_SITE = quote("Request from hr.radarexec.ru website")
SUBJ_LAB = quote("Application for on-site laboratory")
SUBJ_ONLINE = quote("Online program — 2.5 months")

def apply_replacements(text, pairs):
    for old, new in pairs:
        text = text.replace(old, new)
    return text

INDEX_PAIRS = [
    ('<html lang="ru">', '<html lang="en">'),
    ('<title>HR-партнер нового контура — программа подготовки HR 2026</title>',
     '<title>HR Partner of the New Contour — HR Training Program 2026</title>'),
    ('src="assets/images/', 'src="../assets/images/'),
    ('<div class="nav-logo">HR — Новый Контур</div>', '<div class="nav-logo">HR — New Contour</div>'),
    ('''    <div class="lang-switch">
      <a href="index.html" class="lang-switch__link lang-switch__link--active" hreflang="ru" aria-current="true">RU</a>
      <span class="lang-switch__sep">|</span>
      <a href="en/index.html" class="lang-switch__link" hreflang="en">EN</a>
    </div>''',
     '''    <div class="lang-switch">
      <a href="../index.html" class="lang-switch__link" hreflang="ru">RU</a>
      <span class="lang-switch__sep">|</span>
      <a href="index.html" class="lang-switch__link lang-switch__link--active" hreflang="en" aria-current="true">EN</a>
    </div>'''),
    ('subject=%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81%20%D1%81%20%D1%81%D0%B0%D0%B9%D1%82%D0%B0%20radarexec.ru', f'subject={SUBJ_SITE}'),
    ('subject=%D0%97%D0%B0%D1%8F%D0%B2%D0%BA%D0%B0%20%D0%BD%D0%B0%20%D0%B2%D1%8B%D0%B5%D0%B7%D0%B4%D0%BD%D1%83%D1%8E%20%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D1%8E', f'subject={SUBJ_LAB}'),
    ('subject=%D0%9E%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%20%E2%80%94%202%2C5%20%D0%BC%D0%B5%D1%81%D1%8F%D1%86%D0%B0', f'subject={SUBJ_ONLINE}'),
    ('title="Откроется ваша почтовая программа с готовым письмом"', 'title="Opens your email client with a pre-filled message"'),
    ('<li><a href="#problem">Проблема</a></li>', '<li><a href="#problem">Challenge</a></li>'),
    ('<li><a href="#program">Программа</a></li>', '<li><a href="#program">Program</a></li>'),
    ('<li><a href="#formats">Форматы</a></li>', '<li><a href="#formats">Formats</a></li>'),
    ('<li><a href="#artifacts">Результаты</a></li>', '<li><a href="#artifacts">Outcomes</a></li>'),
    ('<li><a href="#audience">Для кого</a></li>', '<li><a href="#audience">Audience</a></li>'),
    ('<li><a href="#mission">Миссия</a></li>', '<li><a href="#mission">Mission</a></li>'),
    ('<li><a href="#experts">Команда</a></li>', '<li><a href="#experts">Team</a></li>'),
    ('>Оставить заявку<', '>Request info<'),
    ('Программа подготовки HR-директоров и HR-бизнес-партнёров · 2026',
     'HR Director &amp; HR Business Partner Training Program · 2026'),
    ('<h1>HR-партнер<br><em>нового</em><br>контура</h1>',
     '<h1>HR Partner<br>of the <em>New</em><br>Contour</h1>'),
    ('Автоматизация, импортозамещение HR-сервисов, knowledge management, ESG, инклюзия и интеграция вернувшихся с СВО. Переход от кадрового оформления к управленческой архитектуре.',
     'Automation, HR service localization, knowledge management, ESG, inclusion, and integration of veterans returning from the SMO. A shift from personnel administration to management architecture.'),
    ('>Выбрать формат<', '>Choose a format<'),
    ('>Подробнее о программе<', '>Program details<'),
    ('alt="Юлия Гордеева — автор программы"', 'alt="Yulia Gordeeva — program author"'),
    ('Юлия Гордеева — автор и ведущая программы', 'Yulia Gordeeva — author and lead facilitator'),
    ('Год, когда бизнес уже требует от HR роль управленческого партнёра — не кадровика',
     'The year when business already expects HR to be a management partner — not a clerk'),
    ('практических контуров программы', 'practical program contours'),
    ('дней выездной лаборатории', 'days on-site laboratory'),
    ('модулей онлайн-программы', 'online program modules'),
    ('недели сопровождения внедрения', 'weeks of implementation support'),
    ('Диагностика рынка', 'Market diagnosis'),
    ('<h2>5 болей, которые<br>разрушают HR-функцию</h2>',
     '<h2>5 pains that<br>undermine the HR function</h2>'),
    ('Бизнес ожидает управленческого партнёра. Рынок предлагает кадровых оформителей. Это расстояние и есть точка входа программы.',
     'Business expects a management partner. The market offers personnel clerks. That gap is where this program begins.'),
    ('<h3>Нехватка компетентных HR</h3>',
     '<h3>Shortage of competent HR professionals</h3>'),
    ('Много специалистов по кадровым документам — мало тех, кто говорит с руководством на языке целей, рисков и метрик. HR остаётся «отделом оформления».',
     'Many specialists in personnel paperwork — few who speak to leadership in the language of goals, risks, and metrics. HR remains a "paperwork department."'),
    ('<h3>Провал в аналитике</h3>', '<h3>Analytics failure</h3>'),
    ('Excel вместо HR-дашбордов, ручной подбор вместо управляемой воронки, нет прозрачной аналитики. HR не умеет мыслить процессно и цифрами.',
     'Excel instead of HR dashboards, manual hiring instead of a managed funnel, no transparent analytics. HR cannot think in processes and numbers.'),
    ('<h3>Импортозамещение без HR</h3>', '<h3>Localization without HR</h3>'),
    ('Компании заменяют сервисы, а HR не может описать процесс, сформулировать ТЗ или провести внедрение без саботажа. Итог — цифровая имитация.',
     'Companies replace services while HR cannot describe the process, draft requirements, or implement change without sabotage. The result is digital theater.'),
    ('<h3>Саботаж изменений</h3>', '<h3>Change sabotage</h3>'),
    ('«У нас так не принято», «люди не будут пользоваться», «это не зона HR». Вместо агента изменений — точка сопротивления, которая увеличивает нагрузку на бизнес.',
     '"That\'s not how we do things," "people won\'t use it," "that\'s not HR\'s job." Instead of a change agent — a point of resistance that increases the burden on the business.'),
    ('<h3>Потеря корпоративных знаний</h3>', '<h3>Loss of corporate knowledge</h3>'),
    ('Знания — в головах сотрудников, в чатах и старых папках. При уходе ключевых людей компания теряет инструкции, логику решений и управленческую память.',
     'Knowledge lives in employees\' heads, chats, and old folders. When key people leave, the company loses instructions, decision logic, and management memory.'),
    ('<h3 style="color: var(--white);">Что меняет программа</h3>',
     '<h3 style="color: var(--white);">What the program changes</h3>'),
    ('Она переводит HR-специалистов в новую управленческую роль, которую бизнес уже требует сегодня. Не «лучше вести кадровую работу» — а стать архитектором HR-функции.',
     'It moves HR professionals into the new management role business already demands today. Not "do personnel work better" — but become architects of the HR function.'),
    ('>Обсудить задачу<', '>Discuss your challenge<'),
    ('>Смотреть форматы программы<', '>View program formats<'),
    ('Нажатие откроет вашу почтовую программу с готовым письмом.',
     'Clicking will open your email client with a pre-filled message.'),
    ('Архитектура программы', 'Program architecture'),
    ('<h2>Шесть контуров нового HR</h2>', '<h2>Six contours of the new HR</h2>'),
    ('Программа строится вокруг шести практических контуров. Каждый — это реальные навыки, применимые с первого дня после обучения.',
     'The program is built around six practical contours. Each delivers real skills applicable from day one after training.'),
    ('Ключевое преимущество', 'Key advantage'),
    ('Выпускник умеет видеть HR как часть управленческого контура компании, предлагать конкретные решения, описывать и автоматизировать процессы, участвовать в импортозамещении, создавать базы знаний и вести социально значимые проекты как управленческие.',
     'Graduates see HR as part of the company\'s management contour, propose concrete solutions, describe and automate processes, participate in service localization, build knowledge bases, and run socially significant projects as management initiatives.'),
    ('<h4>HR как управленческий партнёр</h4>', '<h4>HR as a management partner</h4>'),
    ('Понимание управленческого контура, формулировка HR-предложения для руководства, защита инициатив, бюджетов и изменений. Переход от исполнителя заявок к участнику управленческих решений.',
     'Understanding the management contour, framing HR proposals for leadership, defending initiatives, budgets, and change. Moving from request executor to participant in management decisions.'),
    ('<h4>Автоматизация и импортозамещение</h4>', '<h4>Automation and service localization</h4>'),
    ('Работа с HR-процессами как продуктами: подбор, адаптация, обучение, ЭДО, аналитика, внутренние коммуникации. Практический результат — мини-ТЗ на автоматизацию.',
     'Treating HR processes as products: hiring, onboarding, training, e-document flow, analytics, internal communications. Practical outcome — a mini-spec for automation.'),
    ('<h4>HR-аналитика и прозрачность</h4>', '<h4>HR analytics and transparency</h4>'),
    ('Текучесть, удержание, вовлечённость, стоимость найма, абсентеизм, ESG-показатели. Прототип HR-дашборда для руководства — финальный артефакт блока.',
     'Turnover, retention, engagement, cost per hire, absenteeism, ESG metrics. An HR dashboard prototype for leadership — the final artifact of this block.'),
    ('<h4>Разумное и ответственное использование ИИ</h4>', '<h4>Responsible use of AI</h4>'),
    ('Применение ИИ-инструментов в подборе, адаптации, аналитике и генерации документов — и понимание границ: где алгоритм ошибается, где нарушается приватность данных, где решение должно оставаться за человеком. HR как ответственный заказчик и контролёр ИИ-решений, а не пассивный пользователь.',
     'Using AI tools in hiring, onboarding, analytics, and document generation — and understanding the limits: where algorithms fail, where data privacy is violated, where the decision must remain human. HR as a responsible buyer and controller of AI solutions, not a passive user.'),
    ('<h4>Инклюзия, интеграция вернувшихся с СВО и ESG</h4>',
     '<h4>Inclusion, veteran integration, and ESG</h4>'),
    ('Организация инклюзивного рабочего пространства, интеграция вернувшихся с СВО, взаимодействие с органами власти и центрами занятости. ESG как система социальных и кадровых метрик, а также выстраивание профессионального взаимодействия с органами власти как отдельная зона ответственности современного HR.',
     'Building an inclusive workplace, integrating veterans returning from the SMO, engaging with government agencies and employment centers. ESG as a system of social and workforce metrics, plus professional engagement with authorities as a distinct responsibility of modern HR.'),
    ('Карта критических знаний, база знаний для адаптации и руководителей, наставничество, передача экспертизы. Внутреннее наставничество и модель «лидеры учат лидеров» как механизм передачи экспертизы внутри компании, снижающий риск потери знаний при уходе ключевых сотрудников. Архитектура корпоративной базы знаний — как итоговый артефакт.',
     'Critical knowledge map, knowledge base for onboarding and managers, mentoring, expertise transfer. Internal mentoring and a "leaders teach leaders" model as a mechanism for transferring expertise inside the company, reducing the risk of knowledge loss when key employees leave. Corporate knowledge base architecture as the final artifact.'),
    ('>Выбрать формат обучения<', '>Choose a training format<'),
    ('Форматы участия', 'Participation formats'),
    ('<h2>Выберите формат<br>под вашу задачу</h2>', '<h2>Choose the format<br>for your challenge</h2>'),
    ('Выездная лаборатория — для быстрого результата на базе заказчика. Онлайн-программа — для глубокой перестройки компетенций команды.',
     'On-site laboratory — for fast results at the client\'s location. Online program — for deep rebuilding of team competencies.'),
    ('>Выездная лаборатория<', '>On-site laboratory<'),
    ('>Онлайн-программа<', '>Online program<'),
    ('Фаза 1 — До старта', 'Phase 1 — Before launch'),
    ('<h4>Экспресс-диагностика (10 дней)</h4>', '<h4>Express diagnostics (10 days)</h4>'),
    ('Сбор данных о HR-процессах, провалах в подборе и адаптации, сервисах под замену, наличии базы знаний и ожиданиях руководства. Результат: карта приоритетных задач лаборатории.',
     'Collecting data on HR processes, hiring and onboarding gaps, services to replace, knowledge base status, and leadership expectations. Outcome: a map of laboratory priorities.'),
    ('Фаза 2 — Интенсив', 'Phase 2 — Intensive'),
    ('<h4>10 дней на площадке заказчика</h4>', '<h4>10 days at the client site</h4>'),
    ('5 дней обучения + 5 проектных сессий по внедрению. Каждый день — конкретный артефакт на реальных процессах компании.',
     '5 days of training + 5 implementation project sessions. Each day — a concrete artifact on the company\'s real processes.'),
    ('Фаза 3 — Внедрение', 'Phase 3 — Implementation'),
    ('<h4>4 недели сопровождения</h4>', '<h4>4 weeks of support</h4>'),
    ('Еженедельные онлайн-сессии, проектные консультации, разбор сопротивления, корректировка ТЗ. Цель: запустить минимум один практический результат за 4 недели.',
     'Weekly online sessions, project consulting, resistance work, spec adjustments. Goal: launch at least one practical result within 4 weeks.'),
    ('<summary>Показать подробную программу по дням — 10 дней</summary>',
     '<summary>Show detailed 10-day program</summary>'),
    ('<div class="day-num">День ', '<div class="day-num">Day '),
    ('<h5>Управленческий контур HR</h5>', '<h5>HR management contour</h5>'),
    ('Почему старый HR не работает. Как руководители оценивают HR. Формулировка управленческого предложения.',
     'Why old HR fails. How leaders evaluate HR. Framing a management proposal.'),
    ('▸ Матрица перехода к управленческому партнёру', '▸ Transition matrix to management partner'),
    ('<h5>HR-процессы и точки потерь</h5>', '<h5>HR processes and loss points</h5>'),
    ('Описание реальных HR-процессов заказчика, выявление ручных операций и дублирований, фиксация потерь.',
     'Mapping the client\'s real HR processes, identifying manual operations and duplication, recording losses.'),
    ('▸ Карта HR-процессов и тепловая карта потерь', '▸ HR process map and loss heat map'),
    ('<h5>Автоматизация, импортозамещение и ИИ в HR</h5>', '<h5>Automation, localization, and AI in HR</h5>'),
    ('Выбор процесса, описание целевого состояния, подготовка требований к сервису, сборка списка задач на автоматизацию. Практика: где в HR-процессах уместен ИИ (скрининг резюме, чат-боты адаптации, генерация первичных документов), а где нужен человеческий контроль. Оценка рисков алгоритмической предвзятости.',
     'Process selection, target state description, service requirements, automation backlog. Practice: where AI fits in HR (resume screening, onboarding chatbots, document generation) and where human control is required. Assessing algorithmic bias risks.'),
    ('▸ Мини-ТЗ на автоматизацию HR-сервиса', '▸ Mini-spec for HR service automation'),
    ('<h5>HR-аналитика без страха</h5>', '<h5>HR analytics without fear</h5>'),
    ('Показатели для руководства, простой HR-дашборд без BI, источники данных, проблемы качества данных.',
     'Metrics for leadership, a simple HR dashboard without BI, data sources, data quality issues.'),
    ('▸ Прототип HR-дашборда для руководства', '▸ HR dashboard prototype for leadership'),
    ('Карта критических знаний, структура базы, первые разделы, модель ответственности за обновление. Внутреннее наставничество и модель «лидеры учат лидеров».',
     'Critical knowledge map, base structure, first sections, update ownership model. Internal mentoring and "leaders teach leaders."'),
    ('▸ Архитектура корпоративной базы знаний', '▸ Corporate knowledge base architecture'),
    ('<h5>Инклюзия, интеграция вернувшихся с СВО и ESG</h5>', '<h5>Inclusion, veteran integration, and ESG</h5>'),
    ('Маршрут интеграции сотрудника, карта рисков, карта партнёров, взаимодействие с органами власти.',
     'Employee integration route, risk map, partner map, engagement with authorities.'),
    ('▸ Паспорт ESG/интеграционного проекта', '▸ ESG/integration project passport'),
    ('<h5>Проектная сессия — автоматизация и ИИ</h5>', '<h5>Project session — automation and AI</h5>'),
    ('Внедрение мини-ТЗ, тестирование решений, работа с сопротивлением пользователей, корректировка списка задач.',
     'Implementing the mini-spec, testing solutions, working with user resistance, adjusting the task list.'),
    ('▸ Пилот автоматизации HR-сервиса', '▸ HR service automation pilot'),
    ('<h5>Проектная сессия — аналитика и дашборд</h5>', '<h5>Project session — analytics and dashboard</h5>'),
    ('Настройка метрик, подключение источников данных, презентация прототипа руководству, сбор обратной связи.',
     'Configuring metrics, connecting data sources, presenting the prototype to leadership, gathering feedback.'),
    ('▸ Рабочий прототип HR-дашборда', '▸ Working HR dashboard prototype'),
    ('<h5>Проектная сессия — база знаний</h5>', '<h5>Project session — knowledge base</h5>'),
    ('Запуск разделов базы, назначение ответственных, модель наставничества, передача экспертизы.',
     'Launching base sections, assigning owners, mentoring model, expertise transfer.'),
    ('▸ Запущенная архитектура базы знаний', '▸ Launched knowledge base architecture'),
    ('<h5>Защита дорожной карты</h5>', '<h5>Roadmap defense</h5>'),
    ('Команды выходят к руководству с конкретным предложением: процесс, данные, решение, ресурсы, эффект через 90 дней.',
     'Teams present to leadership with a concrete proposal: process, data, solution, resources, 90-day impact.'),
    ('▸ Дорожная карта HR-трансформации на 90 дней', '▸ 90-day HR transformation roadmap'),
    ('<div class="day-num" style="color: var(--gold);">+ 4 недели</div>',
     '<div class="day-num" style="color: var(--gold);">+ 4 weeks</div>'),
    ('<h5>Сопровождение внедрения</h5>', '<h5>Implementation support</h5>'),
    ('1 онлайн-сессия в неделю. Минимум один запущенный результат: дашборд, база знаний, проект автоматизации, программа интеграции СВО.',
     '1 online session per week. At least one launched result: dashboard, knowledge base, automation project, veteran integration program.'),
    ('▸ Контроль запуска пилота', '▸ Pilot launch control'),
    ('<div class="phase-tag">Длительность</div>', '<div class="phase-tag">Duration</div>'),
    ('<h4>2,5 месяца</h4>', '<h4>2.5 months</h4>'),
    ('Еженедельные live-сессии с практическими воркшопами на реальных процессах компании.',
     'Weekly live sessions with practical workshops on the company\'s real processes.'),
    ('<div class="phase-tag">Структура</div>', '<div class="phase-tag">Structure</div>'),
    ('<h4>13 модулей</h4>', '<h4>13 modules</h4>'),
    ('Домашние задания на реальных процессах компании. Шаблоны документов и финальная защита проекта.',
     'Homework on real company processes. Document templates and final project defense.'),
    ('<div class="phase-tag">Итог</div>', '<div class="phase-tag">Outcome</div>'),
    ('<h4>Готовый HR-проект</h4>', '<h4>Ready HR project</h4>'),
    ('Защита реального проекта: дашборд, база знаний, программа интеграции, дорожная карта трансформации.',
     'Defense of a real project: dashboard, knowledge base, integration program, transformation roadmap.'),
    ('<summary>Показать все 13 модулей онлайн-программы</summary>',
     '<summary>Show all 13 online program modules</summary>'),
    ('<div class="mod-num">МОДУЛЬ ', '<div class="mod-num">MODULE '),
    ('<h5>Почему старый HR не работает</h5>', '<h5>Why old HR fails</h5>'),
    ('Роль HR в 2026 году. Почему КДП недостаточно. Личная карта профессионального перехода.',
     'The role of HR in 2026. Why personnel administration alone is not enough. Personal professional transition map.'),
    ('<h5>Управленческий контур компании</h5>', '<h5>Company management contour</h5>'),
    ('Как принимаются решения. Язык рисков, целей, ресурсов. Шаблон HR-предложения для руководства.',
     'How decisions are made. The language of risks, goals, resources. HR proposal template for leadership.'),
    ('<h5>Диагностика HR-процессов</h5>', '<h5>HR process diagnostics</h5>'),
    ('Как описывать процессы, где возникают потери. Почему нельзя автоматизировать хаос.',
     'How to describe processes and where losses occur. Why you cannot automate chaos.'),
    ('<h5>Автоматизация HR и ИИ</h5>', '<h5>HR automation and AI</h5>'),
    ('Что автоматизировать в первую очередь. Список приоритетов автоматизации. HR как заказчик цифровых решений. Возможности и границы применения ИИ в подборе, адаптации, кадровом делопроизводстве и аналитике. Риски: предвзятость алгоритмов, утечка персональных данных, ответственность за автоматизированные решения. Чек-лист ответственного внедрения ИИ-инструментов.',
     'What to automate first. Automation priority list. HR as buyer of digital solutions. Opportunities and limits of AI in hiring, onboarding, personnel records, and analytics. Risks: algorithmic bias, personal data leaks, accountability for automated decisions. Responsible AI implementation checklist.'),
    ('<h5>Импортозамещение HR-сервисов</h5>', '<h5>HR service localization</h5>'),
    ('Замена сервисов аналитики, подбора, обучения. Описание требований, сравнение решений, снижение сопротивления.',
     'Replacing analytics, hiring, and training services. Requirements, solution comparison, reducing resistance.'),
    ('Показатели для руководства. Простой HR-дашборд. Прозрачность HR-решений.',
     'Metrics for leadership. A simple HR dashboard. Transparency of HR decisions.'),
    ('<h5>Мотивация, вовлечённость, удержание</h5>', '<h5>Motivation, engagement, retention</h5>'),
    ('Прозрачные показатели мотивации. Карта факторов удержания и связь с руководителем.',
     'Transparent motivation metrics. Retention factor map and link to line managers.'),
    ('Корпоративная база знаний, сохранение экспертизы, связь с адаптацией и кадровым резервом. Внутреннее наставничество и модель «лидеры учат лидеров» как механизм передачи экспертизы внутри компании, снижающий риск потери знаний при уходе ключевых сотрудников.',
     'Corporate knowledge base, preserving expertise, link to onboarding and talent pipeline. Internal mentoring and "leaders teach leaders" as a mechanism for transferring expertise inside the company, reducing knowledge loss when key employees leave.'),
    ('<h5>HR как агент изменений</h5>', '<h5>HR as a change agent</h5>'),
    ('Работа с сопротивлением. Запуск пилотов. Обучение пользователей. Сопровождение внедрения.',
     'Working with resistance. Launching pilots. User training. Implementation support.'),
    ('<h5>Инклюзивное рабочее пространство</h5>', '<h5>Inclusive workplace</h5>'),
    ('Аудит пространства, коммуникаций и цифровой среды. Чек-лист инклюзивного рабочего пространства.',
     'Audit of space, communications, and digital environment. Inclusive workplace checklist.'),
    ('<h5>Интеграция вернувшихся с СВО</h5>', '<h5>Integration of veterans returning from the SMO</h5>'),
    ('Маршрут интеграции. Риски стигматизации. Взаимодействие с внешними партнёрами.',
     'Integration route. Stigmatization risks. Engagement with external partners.'),
    ('<h5>ESG для HR</h5>', '<h5>ESG for HR</h5>'),
    ('ESG как социально-управленческая рамка. Социальные и кадровые метрики. Паспорт ESG-проекта как итоговый артефакт.',
     'ESG as a social-management framework. Social and workforce metrics. ESG project passport as the final artifact.'),
    ('<h5>Взаимодействие с органами власти (GR)</h5>', '<h5>Engagement with authorities (GR)</h5>'),
    ('Формирование профессиональных компетенций для работы с органами государственной власти РФ: коммуникация с центрами занятости, участие в программах государственной поддержки занятости, кадровая отчётность перед госорганами, работа с региональными органами труда и социальной защиты. Паспорт GR-проекта как итоговый артефакт.',
     'Building professional competencies for working with Russian government authorities: employment centers, state employment support programs, workforce reporting to agencies, regional labor and social protection bodies. GR project passport as the final artifact.'),
    ('>Заявка на выездную лабораторию<', '>Apply for on-site laboratory<'),
    ('>Онлайн-программа — 2,5 месяца<', '>Online program — 2.5 months<'),
    ('Кнопки заявки откроют вашу почтовую программу с готовым письмом.',
     'Application buttons will open your email client with a pre-filled message.'),
    ('Бизнес-результаты', 'Business outcomes'),
    ('<h2>Что получает компания<br>на выходе</h2>', '<h2>What the company<br>gets at the end</h2>'),
    ('Не красивые презентации — конкретные артефакты, которые сразу начинают работать.',
     'Not polished slides — concrete artifacts that start working immediately.'),
    ('<h4>Прототип HR-дашборда</h4>', '<h4>HR dashboard prototype</h4>'),
    ('Настроенные метрики для принятия управленческих решений: текучесть, удержание, адаптация, стоимость найма.',
     'Configured metrics for management decisions: turnover, retention, onboarding, cost per hire.'),
    ('<h4>Мини-ТЗ на автоматизацию</h4>', '<h4>Mini-spec for automation</h4>'),
    ('Готовые спецификации для замены или пересборки HR-сервисов без саботажа и хаоса.',
     'Ready specifications for replacing or rebuilding HR services without sabotage or chaos.'),
    ('<h4>Архитектура базы знаний</h4>', '<h4>Knowledge base architecture</h4>'),
    ('Готовая структура, план запуска и передача корпоративной экспертизы в управляемый формат.',
     'Ready structure, launch plan, and transfer of corporate expertise into a manageable format.'),
    ('<h4>Маршрут интеграции СВО</h4>', '<h4>Veteran integration route</h4>'),
    ('Регламент адаптации новых категорий сотрудников. Социальная ответственность как HR-продукт.',
     'Onboarding regulations for new employee categories. Social responsibility as an HR product.'),
    ('<h4>Паспорт ESG-проекта</h4>', '<h4>ESG project passport</h4>'),
    ('Пошаговый план трансформации HR-функции с учётом социальных, кадровых и репутационных метрик.',
     'Step-by-step HR transformation plan accounting for social, workforce, and reputation metrics.'),
    ('<span class="artifact-tag">онлайн-программа</span>', '<span class="artifact-tag">online program</span>'),
    ('Стратегия взаимодействия с органами власти: центры занятости, программы господдержки, кадровая отчётность.',
     'Strategy for engaging authorities: employment centers, state support programs, workforce reporting.'),
    ('<h4>Система наставничества</h4>', '<h4>Mentoring system</h4>'),
    ('Работающая модель передачи экспертизы «лидеры учат лидеров» и профессиональная дорожная карта роста сотрудника внутри компании.',
     'A working "leaders teach leaders" expertise transfer model and a professional growth roadmap inside the company.'),
    ('<h4>Дорожная карта на 90 дней</h4>', '<h4>90-day roadmap</h4>'),
    ('Конкретный план изменений с защитой перед руководством: что, зачем, сколько стоит, какой эффект.',
     'A concrete change plan defended before leadership: what, why, cost, expected impact.'),
    ('>Получить такие результаты<', '>Get these outcomes<'),
    ('>Узнать, как это работает<', '>See how it works<'),
    ('Для кого программа', 'Who the program is for'),
    ('<h2>Те, кому бизнес<br>уже предъявляет<br>новые требования</h2>',
     '<h2>Those whom business<br>already holds to<br>new standards</h2>'),
    ('Программа нужна не для тех, кто хочет «прокачать кадровую работу». Она для тех, кто готов занять управленческую позицию в HR.',
     'This program is not for those who want to "improve personnel work." It is for those ready to take a management position in HR.'),
    ('<span>Корпоративные HR-команды</span>', '<span>Corporate HR teams</span>'),
    ('<span>HRD и руководители HR-направлений</span>', '<span>HRDs and heads of HR functions</span>'),
    ('<span>Специалисты центров занятости</span>', '<span>Employment center specialists</span>'),
    ('<span>Региональные команды по работе с работодателями</span>', '<span>Regional employer engagement teams</span>'),
    ('<span>Корпоративные университеты</span>', '<span>Corporate universities</span>'),
    ('<span>Проектные команды по инклюзии и интеграции</span>', '<span>Inclusion and integration project teams</span>'),
    ('<span>Работодатели, которым нужно быстро усилить HR-функцию</span>', '<span>Employers who need to strengthen HR quickly</span>'),
    ('<span>Женщины в регионах, ищущие смену профессии</span>', '<span>Women in regions seeking a career change</span>'),
    ('<span>Соискатели без опыта в HR, готовые войти в профессию через аналитику и цифровые инструменты</span>',
     '<span>Job seekers without HR experience, ready to enter the profession through analytics and digital tools</span>'),
    ('>Подходит ли мне программа?<', '>Is this program right for me?<'),
    ('>Программа для регионов<', '>Program for regions<'),
    ('Социальная миссия', 'Social mission'),
    ('<h2>Другой выбор для женщин в регионах</h2>', '<h2>A different choice for women in regions</h2>'),
    ('Профессия HR и рекрутинг — один из немногих карьерных путей с низким порогом входа и высоким спросом на рынке труда. Не требует профильного диплома, стартует с базовых аналитических и цифровых навыков — и открывает совершенно другой уровень возможностей, чем работа продавщицей в магазине или оператором пункта выдачи заказов.',
     'HR and recruiting is one of the few career paths with a low entry barrier and high labor market demand. No specialized degree required — it starts with basic analytical and digital skills — and opens a completely different level of opportunity than working as a shop assistant or parcel pickup operator.'),
    ('<h4>Низкий порог входа, высокий потолок роста</h4>', '<h4>Low entry barrier, high growth ceiling</h4>'),
    ('От рекрутера до HR-бизнес-партнёра и HRD.', 'From recruiter to HR business partner and HRD.'),
    ('<h4>Цифровые и аналитические навыки</h4>', '<h4>Digital and analytical skills</h4>'),
    ('Работа с дашбордами, ИИ-инструментами и HR-системами, а не только с бумажными анкетами.',
     'Working with dashboards, AI tools, and HR systems — not just paper forms.'),
    ('<h4>Гибкость и удалённость</h4>', '<h4>Flexibility and remote work</h4>'),
    ('Многие HR-задачи (аналитика, подбор, коммуникации) можно выполнять удалённо, что расширяет географию трудоустройства для женщин в регионах.',
     'Many HR tasks (analytics, hiring, communications) can be done remotely, expanding employment geography for women in regions.'),
    ('Наша социальная миссия — расширить горизонт выбора профессии для женщин в регионах России.',
     'Our social mission is to broaden career choices for women in Russia\'s regions.'),
    ('Команда проекта уже имеет практический опыт карьерной поддержки уязвимых групп — от партнёрств с центрами занятости до карьерных интенсивов для слушателей с ОВЗ. <a href="#expert-lada">Подробнее о команде →</a>',
     'The project team already has practical experience supporting vulnerable groups — from employment center partnerships to career intensives for people with disabilities. <a href="#expert-lada">More about the team →</a>'),
    ('>Узнать о программе для регионов<', '>Learn about the regional program<'),
    ('>Познакомиться с командой<', '>Meet the team<'),
    ('Экспертиза и команда', 'Expertise and team'),
    ('<h2>Кто стоит за программой</h2>', '<h2>Who stands behind the program</h2>'),
    ('Практики с опытом в HR, бизнес-образовании, работе с госсектором и социальными проектами — не теоретики, а те, кто уже реализовывал подобные задачи.',
     'Practitioners with experience in HR, business education, the public sector, and social projects — not theorists, but people who have already delivered similar work.'),
    ('alt="Юлия Гордеева — спикер и идейный вдохновитель программы"',
     'alt="Yulia Gordeeva — speaker and program visionary"'),
    ('<div class="expert-role">Спикер, идейный вдохновитель</div>', '<div class="expert-role">Speaker, program visionary</div>'),
    ('<h3>Юлия Гордеева</h3>', '<h3>Yulia Gordeeva</h3>'),
    ('15+ лет в бизнес-образовании · 60+ корпоративных программ · Россия, Европа, Азия, MENA',
     '15+ years in business education · 60+ corporate programs · Russia, Europe, Asia, MENA'),
    ('Преподавала HR и организационное поведение в Президентской программе подготовки управленческих кадров и на MBA в РЭУ им. Г.В. Плеханова (2008–2022)',
     'Taught HR and organizational behavior in the Presidential Management Training Program and MBA at Plekhanov Russian University of Economics (2008–2022)'),
    ('Разрабатывает и ведёт авторские программы для бизнеса совместно с РАНХиГС, РУДН, Финансовым университетом при Правительстве РФ',
     'Designs and delivers proprietary business programs with RANEPA, RUDN, and the Financial University under the Government of the Russian Federation'),
    ('С 2022 года консультирует и обучает на международных проектах — российских, азиатских и MENA',
     'Since 2022, consults and trains on international projects — Russian, Asian, and MENA'),
    ('Сертифицированный коуч ICF, ментор MBA-программ', 'ICF-certified coach, MBA program mentor'),
    ('🏆 Победитель Всероссийского конкурса бизнес-школ «Лучшие практики управленческого образования 2024»',
     '🏆 Winner of the national business school competition "Best Practices in Management Education 2024"'),
    ('>Подробнее об опыте →<', '>More about experience →<'),
    ('alt="Лада Кузминская — директор по развитию программы"', 'alt="Lada Kuzminskaya — program development director"'),
    ('<div class="expert-role">Директор по развитию</div>', '<div class="expert-role">Development director</div>'),
    ('<h3>Лада Кузминская</h3>', '<h3>Lada Kuzminskaya</h3>'),
    ('12+ лет в управлении образовательными проектами · 150+ реализованных программ',
     '12+ years managing educational projects · 150+ programs delivered'),
    ('Руководила портфелем из 150+ образовательных программ (MBA, профпереподготовка) в АНО ДПО «Московская Бизнес Академия»',
     'Led a portfolio of 150+ educational programs (MBA, professional retraining) at ANO DPO Moscow Business Academy'),
    ('Выстраивала партнёрства с государственным сектором: Центр занятости населения Москвы, Всероссийская ярмарка вакансий, карьерные интенсивы для слушателей с ОВЗ',
     'Built partnerships with the public sector: Moscow Employment Center, All-Russian Job Fair, career intensives for people with disabilities'),
    ('Реализовала госконтракты и тендеры (включая программу GenerationS с РВК) на сумму более 24 млн руб.',
     'Delivered government contracts and tenders (including the GenerationS program with RVC) totaling over 24 million rubles'),
    ('🏆 2024 — победитель конкурса «Лучшие практики управленческого образования» (совместно с Ю. Гордеевой)',
     '🏆 2024 — winner of "Best Practices in Management Education" (with Y. Gordeeva)'),
    ('>Связаться с командой<', '>Contact the team<'),
    ('>Выбрать формат программы<', '>Choose a program format<'),
    ('«Бизнесу больше не нужны кадровики-оформители. Нужны управленческие партнёры, которые умеют работать с <em>данными, автоматизацией и людьми</em>.»',
     '"Business no longer needs personnel clerks. It needs management partners who can work with <em>data, automation, and people</em>."'),
    ('— Юлия Гордеева, автор программы', '— Yulia Gordeeva, program author'),
    ('Эта компетенция нужна не завтра. Она нужна уже сейчас.', 'This competency is not needed tomorrow. It is needed right now.'),
    ('>Начать трансформацию HR<', '>Start HR transformation<'),
    ('Следующий шаг', 'Next step'),
    ('<h2>Растите архитекторов<br>HR-функции внутри компании</h2>',
     '<h2>Grow architects<br>of the HR function<br>inside your company</h2>'),
    ('Выберите формат: выездная лаборатория для быстрой трансформации или онлайн-программа для глубокой перестройки компетенций.',
     'Choose a format: on-site laboratory for fast transformation or online program for deep competency rebuilding.'),
    ('Сейчас откроется ваша почтовая программа с готовым письмом — нажмите «Отправить», чтобы мы получили заявку.',
     'Your email client will open with a pre-filled message — click Send so we receive your request.'),
    ('<div class="footer-brand">HR — Новый Контур · 2026</div>', '<div class="footer-brand">HR — New Contour · 2026</div>'),
    ('Переход от кадрового оформления к управленческой архитектуре',
     'From personnel administration to management architecture'),
    ('ИП Гордеева Юлия Владимировна · ОГРНИП 319774600004492 · ИНН 501304589898<br>',
     'IE Yulia Gordeeva · OGRNIP 319774600004492 · INN 501304589898<br>'),
    ('>Политика обработки персональных данных<', '>Privacy Policy<'),
    ('>Согласие на обработку персональных данных<', '>Personal Data Consent<'),
]

def main():
    src = (ROOT / 'index.html').read_text(encoding='utf-8')
    en = apply_replacements(src, INDEX_PAIRS)
    (ROOT / 'en' / 'index.html').write_text(en, encoding='utf-8')
    print('Wrote en/index.html')

if __name__ == '__main__':
    main()
